sequenceDiagram
  actor U as User
  participant ATM
  participant T
  participant A as Account
  participant C as Cash Dispenser

  activate U
  activate ATM
  U->>ATM : withdraw(account, amount)

  create participant T as Transaction
  activate T
  ATM->>T : withdraw(account, amount)

  activate A
  T->>A : checkout(amount)

  alt account has balance
    A-->>T : return true
    deactivate A
    T-->>ATM : return true
    deactivate T
    destroy T

    activate C
    ATM->>C : withdraw(account, amount)
    C-->>ATM : return amount
    deactivate C

    ATM-->>U : return amount

  else insufficient funds
    A-->>T : return false
    deactivate A
    T-->>ATM : return false
    deactivate T
    destroy T
    ATM-->>U : raise insufficient balance

  deactivate ATM
  deactivate U
