sequenceDiagram
  actor U as User
  participant ATM
  participant T as Transaction
  participant A as Account
  participant C as Cash Dispenser

  activate U
  activate ATM
  U->>ATM : withdraw(account, amount)

  activate T
  ATM->>T : withdraw(account, amount)

  activate A
  T->>A : checkout(amount)

  alt account has balance
    A-->>T : return true
    T-->>ATM : return true
    activate C
    ATM->>C : withdraw(account, amount)
    C-->>ATM : return amount
    deactivate C
    ATM-->>U : return amount
  else insufficient funds
    A-->>T : return false
    T-->>ATM : return false
    ATM-->>U : raise insufficient balance
  end

  deactivate T
  deactivate A
  deactivate ATM
  deactivate U