classDiagram
  class Car {
    <<Abstract>>
    +startEngine()*: void
    +shiftGear(char gear)*: void
    +accelerate()*: void
    +brake()*: void
    +stopEngine()*: void
  }

  class SportsCar {
    +brand: string
    +model: string
    +isEngineOn: bool
    +currentSpeed: int
    +currentGear: char
  }

  Car <|.. SportsCar
