classDiagram
  class Car {
    <<Abstract>>

    -string brand
    -string model
    #int    enginecc

    +startEngine() void
    +stopEngine()  void
    +accelerate()  void
    +brake()       void
  }
